// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBrCXARfwY24LQxwWbMdgQQL0aC_qrluUc',
    appId: '1:745954465107:web:7a56086f3cff7f2319fda6',
    messagingSenderId: '745954465107',
    projectId: 'qr-scanner-e32ec',
    authDomain: 'qr-scanner-e32ec.firebaseapp.com',
    storageBucket: 'qr-scanner-e32ec.firebasestorage.app',
    measurementId: 'G-02RYCD32K9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAHY0rA1228F6qwRnpmAkHOZwq8hzTx030',
    appId: '1:745954465107:android:f87e2026ca4c325719fda6',
    messagingSenderId: '745954465107',
    projectId: 'qr-scanner-e32ec',
    storageBucket: 'qr-scanner-e32ec.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDwDM7iPFqSkDEypJxGqKiWMzkL9DZ03k4',
    appId: '1:745954465107:ios:b4a34e44d43348d819fda6',
    messagingSenderId: '745954465107',
    projectId: 'qr-scanner-e32ec',
    storageBucket: 'qr-scanner-e32ec.firebasestorage.app',
    iosClientId: '745954465107-9g2dfasmq25t0idp6c8954h7bvacqmsa.apps.googleusercontent.com',
    iosBundleId: 'com.example.qrScanner',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDwDM7iPFqSkDEypJxGqKiWMzkL9DZ03k4',
    appId: '1:745954465107:ios:b4a34e44d43348d819fda6',
    messagingSenderId: '745954465107',
    projectId: 'qr-scanner-e32ec',
    storageBucket: 'qr-scanner-e32ec.firebasestorage.app',
    iosClientId: '745954465107-9g2dfasmq25t0idp6c8954h7bvacqmsa.apps.googleusercontent.com',
    iosBundleId: 'com.example.qrScanner',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBrCXARfwY24LQxwWbMdgQQL0aC_qrluUc',
    appId: '1:745954465107:web:647c4e821f6f8d8119fda6',
    messagingSenderId: '745954465107',
    projectId: 'qr-scanner-e32ec',
    authDomain: 'qr-scanner-e32ec.firebaseapp.com',
    storageBucket: 'qr-scanner-e32ec.firebasestorage.app',
    measurementId: 'G-9WQHRLJBTS',
  );
}
